#############################################################################
# Makefile for building: build/blinkers
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  blinkers.pro
# Template: app
# Command: /usr/local/Cellar/qt/5.11.2/bin/qmake -o Makefile blinkers.pro -spec macx-clang CONFIG+=x86_64
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -Ibuild/obj -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.11.2/lib
QMAKE         = /usr/local/Cellar/qt/5.11.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/Cellar/qt/5.11.2/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/Cellar/qt/5.11.2/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = blinkers1.0.0
DISTDIR = /Users/rhad0003/Desktop/2github/Blinkers/Blinkers/build/obj/blinkers1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/5.11.2/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/worker.cpp \
		src/myframe.cpp \
		src/clogbook.cpp \
		src/gct.cpp \
		src/mainwindow.cpp \
		src/myqtextedit.cpp build/obj/moc_worker.cpp \
		build/obj/moc_myframe.cpp \
		build/obj/moc_clogbook.cpp \
		build/obj/moc_mainwindow.cpp
OBJECTS       = build/obj/main.o \
		build/obj/worker.o \
		build/obj/myframe.o \
		build/obj/clogbook.o \
		build/obj/gct.o \
		build/obj/mainwindow.o \
		build/obj/myqtextedit.o \
		build/obj/moc_worker.o \
		build/obj/moc_myframe.o \
		build/obj/moc_clogbook.o \
		build/obj/moc_mainwindow.o
DIST          = /usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/lex.prf \
		blinkers.pro src/worker.h \
		src/utils.h \
		src/myframe.h \
		src/clogbook.h \
		src/gct.h \
		src/mainwindow.h \
		src/myqtextedit.h \
		src/ui_myframe.h \
		src/ui_mainwindow.h src/main.cpp \
		src/worker.cpp \
		src/myframe.cpp \
		src/clogbook.cpp \
		src/gct.cpp \
		src/mainwindow.cpp \
		src/myqtextedit.cpp
QMAKE_TARGET  = blinkers
DESTDIR       = build/
TARGET        = build/blinkers

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.13
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


include /usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d build/ || mkdir -p build/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: blinkers.pro /usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/exceptions.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/5.11.2/mkspecs/features/lex.prf \
		blinkers.pro \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/QtWidgets.prl \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile blinkers.pro -spec macx-clang CONFIG+=x86_64
/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/qdevice.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/macx.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/exceptions.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/5.11.2/mkspecs/features/lex.prf:
blinkers.pro:
/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/QtWidgets.prl:
/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile blinkers.pro -spec macx-clang CONFIG+=x86_64

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/local/Cellar/qt/5.11.2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/worker.h src/utils.h src/myframe.h src/clogbook.h src/gct.h src/mainwindow.h src/myqtextedit.h src/ui_myframe.h src/ui_mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/worker.cpp src/myframe.cpp src/clogbook.cpp src/gct.cpp src/mainwindow.cpp src/myqtextedit.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/obj/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/obj/moc_predefs.h
build/obj/moc_predefs.h: /usr/local/Cellar/qt/5.11.2/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -Wall -W -dM -E -o build/obj/moc_predefs.h /usr/local/Cellar/qt/5.11.2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/obj/moc_worker.cpp build/obj/moc_myframe.cpp build/obj/moc_clogbook.cpp build/obj/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/obj/moc_worker.cpp build/obj/moc_myframe.cpp build/obj/moc_clogbook.cpp build/obj/moc_mainwindow.cpp
build/obj/moc_worker.cpp: /usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDEBUG \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		src/myframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFrame \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		src/clogbook.h \
		src/worker.h \
		build/obj/moc_predefs.h \
		/usr/local/Cellar/qt/5.11.2/bin/moc
	/usr/local/Cellar/qt/5.11.2/bin/moc $(DEFINES) --include /Users/rhad0003/Desktop/2github/Blinkers/Blinkers/build/obj/moc_predefs.h -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -I/Users/rhad0003/Desktop/2github/Blinkers/Blinkers -I/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.11.2/lib src/worker.h -o build/obj/moc_worker.cpp

build/obj/moc_myframe.cpp: /usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFrame \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		src/myframe.h \
		build/obj/moc_predefs.h \
		/usr/local/Cellar/qt/5.11.2/bin/moc
	/usr/local/Cellar/qt/5.11.2/bin/moc $(DEFINES) --include /Users/rhad0003/Desktop/2github/Blinkers/Blinkers/build/obj/moc_predefs.h -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -I/Users/rhad0003/Desktop/2github/Blinkers/Blinkers -I/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.11.2/lib src/myframe.h -o build/obj/moc_myframe.cpp

build/obj/moc_clogbook.cpp: /usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		src/clogbook.h \
		build/obj/moc_predefs.h \
		/usr/local/Cellar/qt/5.11.2/bin/moc
	/usr/local/Cellar/qt/5.11.2/bin/moc $(DEFINES) --include /Users/rhad0003/Desktop/2github/Blinkers/Blinkers/build/obj/moc_predefs.h -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -I/Users/rhad0003/Desktop/2github/Blinkers/Blinkers -I/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.11.2/lib src/clogbook.h -o build/obj/moc_clogbook.cpp

build/obj/moc_mainwindow.cpp: src/myqtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		src/myframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFrame \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		src/clogbook.h \
		src/worker.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDEBUG \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/Qtime \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFormLayout \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QSpinBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qspinbox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qcheckbox.h \
		src/mainwindow.h \
		build/obj/moc_predefs.h \
		/usr/local/Cellar/qt/5.11.2/bin/moc
	/usr/local/Cellar/qt/5.11.2/bin/moc $(DEFINES) --include /Users/rhad0003/Desktop/2github/Blinkers/Blinkers/build/obj/moc_predefs.h -I/usr/local/Cellar/qt/5.11.2/mkspecs/macx-clang -I/Users/rhad0003/Desktop/2github/Blinkers/Blinkers -I/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -F/usr/local/Cellar/qt/5.11.2/lib src/mainwindow.h -o build/obj/moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/main.o: src/main.cpp /usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QApplication \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qapplication.h \
		src/mainwindow.h \
		src/myqtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		src/myframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFrame \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		src/clogbook.h \
		src/worker.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDEBUG \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/Qtime \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFormLayout \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QSpinBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qspinbox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qcheckbox.h \
		src/gct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/worker.o: src/worker.cpp src/worker.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDEBUG \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		src/myframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFrame \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		src/clogbook.h \
		src/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/worker.o src/worker.cpp

build/obj/myframe.o: src/myframe.cpp src/myframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFrame \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		src/ui_myframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/myframe.o src/myframe.cpp

build/obj/clogbook.o: src/clogbook.cpp src/clogbook.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/clogbook.o src/clogbook.cpp

build/obj/gct.o: src/gct.cpp src/gct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/gct.o src/gct.cpp

build/obj/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/myqtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h \
		src/myframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFrame \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qframe.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QColor \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qcolor.h \
		src/clogbook.h \
		src/worker.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDEBUG \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qlabel.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/Qtime \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QGroupBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qgroupbox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QFormLayout \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qformlayout.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QSpinBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qspinbox.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QCheckBox \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qcheckbox.h \
		src/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/mainwindow.o src/mainwindow.cpp

build/obj/myqtextedit.o: src/myqtextedit.cpp src/myqtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/QTextEdit \
		/usr/local/Cellar/qt/5.11.2/lib/QtWidgets.framework/Headers/qtextedit.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/QTime \
		/usr/local/Cellar/qt/5.11.2/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/QPalette \
		/usr/local/Cellar/qt/5.11.2/lib/QtGui.framework/Headers/qpalette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/myqtextedit.o src/myqtextedit.cpp

build/obj/moc_worker.o: build/obj/moc_worker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_worker.o build/obj/moc_worker.cpp

build/obj/moc_myframe.o: build/obj/moc_myframe.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_myframe.o build/obj/moc_myframe.cpp

build/obj/moc_clogbook.o: build/obj/moc_clogbook.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_clogbook.o build/obj/moc_clogbook.cpp

build/obj/moc_mainwindow.o: build/obj/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_mainwindow.o build/obj/moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

